manifest:
  version: 0.7
 
  defaults:
    remote: zephyrproject
  remotes:
    - name: cmake_utils_repo
      url-base: https://github.com/xsession
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos
    - name: mcutools
      url-base: https://github.com/mcu-tools

  projects:
    - name: zephyr
      repo-path: zephyr
      remote: zephyrproject
      revision: main
      import:
        path-prefix: deps
      path: zephyr
    
    - name: mcuboot
      remote: mcutools
      repo-path: mcuboot
      revision: v1.7.2
      path: deps/mcuboot

    - name: cmake_utils
      remote: cmake_utils_repo
      repo-path: cmake_utils
      revision: main
      path: deps/cmake_utils
 
  self:
    path: app